# This file lists the dependencies needed to build and test all of
# darmonpoints. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -f environment.yml
name: sage-flatsurf-build
channels:
  - conda-forge
  - defaults
dependencies:
  - codespell >=2.2.2,<3
  - gap-defaults
  - ipywidgets
  - matplotlib-base
  - pip
  - pytest
  - pytest-xdist
  - sagelib>=8.8
  - sagemath>=1.3.0
  # sagelib<9.2 does not explicitly install libiconv which is needed in lots of places.
  - libiconv
  - pycodestyle >=2.9.1,<3
  - pyeantic>=1,<2  # optional: eantic
  - pyexactreal>=2,<3  # optional: exactreal
  - pyintervalxt>=3,<4  # optional: pyflatsurf
