# This file lists the dependencies needed to build and test all of
# darmonpoints. Create a conda environment with these dependencies
# preinstalled with:
# conda env create -f environment.yml
name: sage-darmonpoints-build
channels:
  - conda-forge
  - defaults
dependencies:
  - codespell >=2.2.2,<3
  - gap-defaults
  - ipywidgets
  - matplotlib-base
  - pip
  - pytest
  - pytest-xdist
  - sagelib>=9.3
  - pycodestyle >=2.9.1,<3


