name: Documentation
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update -n test --quiet -f environment.yml
          conda list
      - name: install package
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .
      - name: build documentation
        shell: bash -l {0}
        run: |
          cd doc
          make html SPHINXOPTS="-n --keep-going"
          # Do not run Jekyll to create GitHub Pages but take HTML files as they are.
          touch _build/html/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/_build/html
          TARGET_FOLDER: docs
        if: ${{ github.event_name == 'push' }}
        
