name: Lint
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "${{ matrix.python }}"
          miniforge-variant: Mambaforge
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: install package
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .
      - name: black
        shell: bash -l {0}
        run: |
          black --check --diff darmonpoints
      - name: isort
        shell: bash -l {0}
        run: |
          isort --check --diff darmonpoints --line-length 256
